/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSubmitBatchIdRouteImport } from './routes/_authenticated/submit/$batchId'
import { Route as AuthenticatedScanBatchIdRouteImport } from './routes/_authenticated/scan/$batchId'
import { Route as AuthenticatedBatchesNewRouteImport } from './routes/_authenticated/batches/new'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubmitBatchIdRoute =
  AuthenticatedSubmitBatchIdRouteImport.update({
    id: '/submit/$batchId',
    path: '/submit/$batchId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScanBatchIdRoute =
  AuthenticatedScanBatchIdRouteImport.update({
    id: '/scan/$batchId',
    path: '/scan/$batchId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBatchesNewRoute = AuthenticatedBatchesNewRouteImport.update({
  id: '/batches/new',
  path: '/batches/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/sign-in': typeof SignInRoute
  '/batches/new': typeof AuthenticatedBatchesNewRoute
  '/scan/$batchId': typeof AuthenticatedScanBatchIdRoute
  '/submit/$batchId': typeof AuthenticatedSubmitBatchIdRoute
}
export interface FileRoutesByTo {
  '/forbidden': typeof ForbiddenRoute
  '/sign-in': typeof SignInRoute
  '/': typeof AuthenticatedIndexRoute
  '/batches/new': typeof AuthenticatedBatchesNewRoute
  '/scan/$batchId': typeof AuthenticatedScanBatchIdRoute
  '/submit/$batchId': typeof AuthenticatedSubmitBatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/sign-in': typeof SignInRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/batches/new': typeof AuthenticatedBatchesNewRoute
  '/_authenticated/scan/$batchId': typeof AuthenticatedScanBatchIdRoute
  '/_authenticated/submit/$batchId': typeof AuthenticatedSubmitBatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/sign-in'
    | '/batches/new'
    | '/scan/$batchId'
    | '/submit/$batchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forbidden'
    | '/sign-in'
    | '/'
    | '/batches/new'
    | '/scan/$batchId'
    | '/submit/$batchId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forbidden'
    | '/sign-in'
    | '/_authenticated/'
    | '/_authenticated/batches/new'
    | '/_authenticated/scan/$batchId'
    | '/_authenticated/submit/$batchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submit/$batchId': {
      id: '/_authenticated/submit/$batchId'
      path: '/submit/$batchId'
      fullPath: '/submit/$batchId'
      preLoaderRoute: typeof AuthenticatedSubmitBatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan/$batchId': {
      id: '/_authenticated/scan/$batchId'
      path: '/scan/$batchId'
      fullPath: '/scan/$batchId'
      preLoaderRoute: typeof AuthenticatedScanBatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/batches/new': {
      id: '/_authenticated/batches/new'
      path: '/batches/new'
      fullPath: '/batches/new'
      preLoaderRoute: typeof AuthenticatedBatchesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBatchesNewRoute: typeof AuthenticatedBatchesNewRoute
  AuthenticatedScanBatchIdRoute: typeof AuthenticatedScanBatchIdRoute
  AuthenticatedSubmitBatchIdRoute: typeof AuthenticatedSubmitBatchIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBatchesNewRoute: AuthenticatedBatchesNewRoute,
  AuthenticatedScanBatchIdRoute: AuthenticatedScanBatchIdRoute,
  AuthenticatedSubmitBatchIdRoute: AuthenticatedSubmitBatchIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
